apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: q0nk5zb7m-python
  janus-idp.io/tekton: q0nk5zb7m-python
  backstage.io/kubernetes-id: q0nk5zb7m-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q0nk5zb7m-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
